#include <stdio.h>

int main(void)
{
	puts("Bem Vindo.");
	puts ("Qual opcao voce deseja usar?");
	puts ("1. Gerenciar itens do cardapio");
	puts ("2. Fazer um Pedido");
	puts ("3. Solicitar Conta");
	puts ("4. Sair do sistema");
	getchar();
	system("sleep 0.35");
	system("clear");
	puts("em Vindo.");
	puts ("ual opcao voce deseja usar?");
	puts (". Gerenciar itens do cardapio");
	puts (". Fazer um Pedido");
	puts (". Solicitar Conta");
	puts (". Sair do sistema");
	system("sleep 0.35");
	system("clear");
	puts("m Vindo.");
	puts ("al opcao voce deseja usar?");
	puts (" Gerenciar itens do cardapio");
	puts (" Fazer um Pedido");
	puts (" Solicitar Conta");
	puts (" Sair do sistema");
	system("sleep 0.35");
	system("clear");
	puts(" Vindo.");
	puts ("l opcao voce deseja usar?");
	puts ("Gerenciar itens do cardapio");
	puts ("Fazer um Pedido");
	puts ("Solicitar Conta");
	puts ("Sair do sistema");
	system("sleep 0.35");
	system("clear");
	puts("Vindo.");
	puts (" opcao voce deseja usar?");
	puts ("erenciar itens do cardapio");
	puts ("azer um Pedido");
	puts ("olicitar Conta");
	puts ("air do sistema");
	system("sleep 0.35");
	system("clear");
	puts("indo.");
	puts ("opcao voce deseja usar?");
	puts ("renciar itens do cardapio");
	puts ("zer um Pedido");
	puts ("licitar Conta");
	puts ("ir do sistema");
	system("sleep 0.35");
	system("clear");
	puts("ndo.");
	puts ("pcao voce deseja usar?");
	puts ("enciar itens do cardapio");
	puts ("er um Pedido");
	puts ("icitar Conta");
	puts ("r do sistema");
	system("sleep 0.35");
	system("clear");
	puts("do.");
	puts ("cao voce deseja usar?");
	puts ("nciar itens do cardapio");
	puts ("r um Pedido");
	puts ("citar Conta");
	puts (" do sistema");
	system("sleep 0.35");
	system("clear");
	puts("o.");
	puts ("ao voce deseja usar?");
	puts ("ciar itens do cardapio");
	puts (" um Pedido");
	puts ("itar Conta");
	puts ("do sistema");
	system("sleep 0.35");
	system("clear");
	puts(".");
	puts ("o voce deseja usar?");
	puts ("iar itens do cardapio");
	puts ("um Pedido");
	puts ("tar Conta");
	puts ("o sistema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts (" voce deseja usar?");
	puts ("ar itens do cardapio");
	puts ("m Pedido");
	puts ("ar Conta");
	puts (" sistema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("voce deseja usar?");
	puts ("r itens do cardapio");
	puts (" Pedido");
	puts ("r Conta");
	puts ("sistema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("oce deseja usar?");
	puts (" itens do cardapio");
	puts ("Pedido");
	puts (" Conta");
	puts ("istema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("ce deseja usar?");
	puts ("itens do cardapio");
	puts ("edido");
	puts ("Conta");
	puts ("stema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("e deseja usar?");
	puts ("tens do cardapio");
	puts ("dido");
	puts ("onta");
	puts ("tema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts (" deseja usar?");
	puts ("ens do cardapio");
	puts ("ido");
	puts ("nta");
	puts ("ema");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("deseja usar?");
	puts ("ns do cardapio");
	puts ("do");
	puts ("ta");
	puts ("ma");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("eseja usar?");
	puts ("s do cardapio");
	puts ("o");
	puts ("a");
	puts ("a");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("seja usar?");
	puts (" do cardapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("eja usar?");
	puts ("do cardapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("ja usar?");
	puts ("o cardapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("a usar?");
	puts (" cardapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts (" usar?");
	puts ("cardapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("usar?");
	puts ("ardapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("sar?");
	puts ("rdapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("ar?");
	puts ("dapio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("r?");
	puts ("apio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts ("?");
	puts ("pio");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts (" ");
	puts ("io");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts (" ");
	puts ("o");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	puts(" ");
	puts (" ");
	puts (" ");
	puts (" ");
	puts (" ");
	puts (" ");
	system("sleep 0.35");
	system("clear");
	return 0;
}

